# Generated by Django 4.0.8 on 2022-10-21 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('type', models.CharField(choices=[('S', 'Stock'), ('CB', 'Corporate Bond'), ('MB', 'Mortgage Bond'), ('OM', 'Other Mbs'), ('AM', 'Other Abs')], default='AM', max_length=2)),
                ('quantity_usd', models.FloatField()),
                ('issued_date', models.DateField()),
                ('active_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControlPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity', models.FloatField()),
                ('quarter_performance', models.FloatField()),
                ('daily_performance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('rank', models.CharField(choices=[('P', 'President'), ('SCS', 'Sc Senior'), ('A', 'Associate')], default='A', max_length=3)),
                ('transactions', models.TextField()),
                ('comission_percentage', models.FloatField()),
                ('overall_performance', models.FloatField()),
                ('control_panel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hfma_app.controlpanel')),
                ('managed_assets', models.ManyToManyField(blank=True, default=None, null=True, to='hfma_app.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('occupation_industry', models.CharField(choices=[('H', 'Health'), ('F', 'Finance'), ('E', 'Energy'), ('T', 'Tourism'), ('RE', 'Real Estate'), ('C', 'Consulting'), ('S', 'Software'), ('O', 'Other')], default='O', max_length=2)),
                ('invested', models.FloatField()),
                ('contract', models.CharField(choices=[('A1', 'Alpha 1'), ('A2', 'Alpha 2'), ('B1', 'Beta 1'), ('B2', 'Beta 2')], default='A1', max_length=2)),
                ('start_date', models.DateField()),
                ('active_status', models.BooleanField(default=True)),
                ('control_panel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hfma_app.controlpanel')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='control_panel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hfma_app.controlpanel'),
        ),
    ]
