# Generated by Django 4.0.8 on 2022-10-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfma_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='managed_assets',
            field=models.ManyToManyField(blank=True, default=None, to='hfma_app.asset'),
        ),
    ]
