# Generated by Django 4.0.8 on 2022-10-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfma_app', '0002_alter_employee_managed_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpanel',
            name='name',
            field=models.TextField(default='ControlPanel.:<function ControlPanel._formated_date at 0x102a695a0>', max_length=20),
        ),
    ]
