# Generated by Django 4.0.8 on 2022-11-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfma_app', '0004_alter_controlpanel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='control_panel',
        ),
        migrations.AddField(
            model_name='controlpanel',
            name='managed_assets',
            field=models.ManyToManyField(blank=True, default=None, to='hfma_app.asset'),
        ),
        migrations.AlterField(
            model_name='controlpanel',
            name='name',
            field=models.TextField(default='ControlPanel.:2-11-2022', max_length=30),
        ),
    ]
