# Generated by Django 4.0.8 on 2022-11-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfma_app', '0005_remove_asset_control_panel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='financial_indicators',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='asset',
            name='financial_news',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='controlpanel',
            name='name',
            field=models.TextField(default='ControlPanel.:8-11-2022', max_length=30),
        ),
    ]
