# Generated by Django 4.0.8 on 2022-11-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hfma_app', '0006_asset_financial_indicators_asset_financial_news_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='financial_indicators',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='financial_news',
        ),
    ]
