# Generated by Django 4.0.8 on 2022-11-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfma_app', '0008_asset_financial_indicators'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='financial_news',
            field=models.JSONField(default='default'),
            preserve_default=False,
        ),
    ]
